
# Ansistrano deployment playbook
---
  # ------------------------------------------------------------------------------------------------
  # Hosts to deploy to (set to all if you want to be able to just limit installation to specific
  # hosts using the `--limit` arg to `ansible-playbook`.
  #
  - hosts: all
    # ----------------------------------------------------------------------------------------------
    # Variables
    #
    vars:
      # Run tasks in this file after creating the symbolic link to the current release
      ansistrano_after_symlink_tasks_file: "{{ playbook_dir }}/install.yml"
    # ----------------------------------------------------------------------------------------------
    # Files containing additional variables
    #
    vars_files:
      - vars.yml
    # ----------------------------------------------------------------------------------------------
    # Ansible roles
    #
    # One or more roles may be from Ansible Galaxy (ansible-galaxy install <user.role>)
    #
    roles:
      # Miniconda installation role
      - role: noaa-nws-cpc.miniconda
      # Ansistrano deployment role
      - role: carlosbuenosvinos.ansistrano-deploy
...

